[package]
name = "firebrust"
version = "0.2.0"
edition = "2024"
license-file = "LICENSE"
publish = false

[lib]
name = "my_rust_parser"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.45"
hex = "0.4.3"
log = "0.4.34"
pyo3 = {version = "0.29.2", features = ["extension-module"]}
rayon = "1.12.0"

[dev-dependencies]
env_logger = "0.11"
